vich_uploader:
  db_driver: orm

  mappings:
    post_image:
      uri_prefix: /images/articles
      upload_destination: "%kernel.project_dir%/public/images/articles"
      namer: Vich\UploaderBundle\Naming\OrignameNamer
